name: crowdsecurity/dawarich-whitelists
description: "Whitelist false positive from dawarich"
whitelist:
  reason: "Whitelist admin paths from dawarich"
  expression:
    - |
      evt.Overflow.Alert.Scenario == "crowdsecurity/http-admin-interface-probing" and
      all(evt.Overflow.Alert.Events, {
        .GetMeta("traefik_router_name") contains "dawarich" and
        .GetMeta("http_verb") == "GET" and
        .GetMeta("http_path") startsWith "/assets/maps_maplibre/managers/"
      })
